export enum DescriptionTypes {
  SET_DESCRIPTIONS = 'SET_DESCRIPTIONS',
  TOGGLE_DESCRIPTION_EXPANDED = 'TOGGLE_DESCRIPTION_EXPANDED',
  HIDE_DELETE_MODAL = 'HIDE_DELETE_MODAL',
  OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL',
  DELETE_DESCRIPTION_CONFIRM = 'DELETE_DESCRIPTION_CONFIRM',
  DELETE_DESCRIPTION_SUCCESS = 'DELETE_DESCRIPTION_SUCCESS',
  ADD_DESCRIPTION = 'ADD_DESCRIPTION',
  ADD_DESCRIPTION_SUCCESS = 'ADD_DESCRIPTION_SUCCESS',
  SELECT_DESCRIPTION_ID = 'SELECT_DESCRIPTION_ID',
  REMOVE_SELECTED_DESCRIPTION_ID = 'REMOVE_SELECTED_DESCRIPTION_ID',
  EDIT_DESCRIPTION = 'EDIT_DESCRIPTION',
}
